version: "3.8"

services:
  django_app:
    build:
      context: .
    image: toda_app_docker
    container_name: toda_app_dj
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0  # Allow access from all platforms
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}  # Secret key from .env file
      - DATABASE_URL=${DATABASE_URL}  # Database URL from .env file
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toda_app_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge
