version: "3.8"

services:
  django_app:
    build:
      context: .
    image: toda_app_compose
    container_name: toda_app_dj
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - toda_app_network

  db:
    image: mysql:5.7
    container_name: db_cont
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=toda_app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - toda_app_network
    restart: always

networks:
  toda_app_network:
    driver: bridge

volumes:
  db_data:

